
# doom engine iwad map names

doom1_maps = {
    'e1m1 - Hangar'                         : 'John Romero',
    'e1m2 - Nuclear Plant'                  : 'John Romero',
    'e1m3 - Toxin Refinery'                 : 'John Romero',
    'e1m4 - Command Control'                : 'John Romero & Tom Hall',
    'e1m5 - Phobos Lab'                     : 'John Romero',
    'e1m6 - Central Processing'             : 'John Romero',
    'e1m7 - Computer Station'               : 'John Romero',
    'e1m8 - Phobos Anomaly'                 : 'Sandy Petersen & Tom Hall',
    'e1m9 - Military Base'                  : 'John Romero',
    'e2m1 - Deimos Anomaly'                 : 'Sandy Petersen & Tom Hall',
    'e2m2 - Containment Area'               : 'Sandy Petersen & Tom Hall',
    'e2m3 - Refinery'                       : 'Sandy Petersen & Tom Hall',
    'e2m4 - Deimos Lab'                     : 'Sandy Petersen & Tom Hall',
    'e2m5 - Command Center'                 : 'Sandy Petersen',
    'e2m6 - Halls of the Damned'            : 'Sandy Petersen',
    'e2m7 - Spawning Vats'                  : 'Sandy Petersen & Tom Hall',
    'e2m8 - Tower of Babel'                 : 'Sandy Petersen',
    'e2m9 - Fortress of Mystery'            : 'Sandy Petersen',
    'e3m1 - Hell Keep'                      : 'Sandy Petersen',
    'e3m2 - Slough of Despair'              : 'Sandy Petersen',
    'e3m3 - Pandemonium'                    : 'Sandy Petersen & Tom Hall',
    'e3m4 - House of Pain'                  : 'Sandy Petersen',
    'e3m5 - Unholy Cathedral'               : 'Sandy Petersen',
    'e3m6 - Mt. Erebus'                     : 'Sandy Petersen',
    'e3m7 - Limbo'                          : 'Sandy Petersen & Tom Hall',
    'e3m8 - Dis'                            : 'Sandy Petersen',
    'e3m9 - Warrens'                        : 'Sandy Petersen',
    'e4m1 - Hell Beneath'                   : 'American McGee',
    'e4m2 - Perfect Hatred'                 : 'John Romero',
    'e4m3 - Sever The Wicked'               : 'Shawn Green',
    'e4m4 - Unruly Evil'                    : 'American McGee',
    'e4m5 - They Will Repent'               : 'Tim Willits',
    'e4m6 - Against Thee Wickedly'          : 'John Romero',
    'e4m7 - And Hell Followed'              : 'John Anderson',
    'e4m8 - Unto The Cruel'                 : 'Shawn Green',
    'e4m9 - Fear'                           : 'Tim Willits'
}

doom2_maps = {
    'map01 - entryway'                      : 'Sandy Petersen',
    'map02 - underhalls'                    : 'American McGee',
    'map03 - the gantlet'                   : 'American McGee',
    'map04 - the focus'                     : 'American McGee',
    'map05 - the waste tunnels'             : 'American McGee',
    'map06 - the crusher'                   : 'American McGee',
    'map07 - dead simple'                   : 'American McGee & Sandy Petersen',
    'map08 - tricks and traps'              : 'Sandy Petersen',
    'map09 - the pit'                       : 'Sandy Petersen',
    'map10 - refueling base'                : 'Sandy Petersen & Tom Hall',
    "map11 - 'o' of destruction!"           : 'John Romero',
    'map12 - the factory'                   : 'Sandy Petersen',
    'map13 - downtown'                      : 'Sandy Petersen',
    'map14 - the inmost dens'               : 'Sandy Petersen',
    'map15 - industrial zone'               : 'John Romero',
    'map16 - suburbs'                       : 'Sandy Petersen',
    'map17 - tenements'                     : 'John Romero',
    'map18 - the courtyard'                 : 'Sandy Petersen',
    'map19 - the citadel'                   : 'Sandy Petersen',
    'map20 - gotcha!'                       : 'John Romero',
    'map21 - nirvana'                       : 'Sandy Petersen',
    'map22 - the catacombs'                 : 'American McGee',
    "map23 - barrels o' fun"                : 'Sandy Petersen',
    'map24 - the chasm'                     : 'Sandy Petersen',
    'map25 - bloodfalls'                    : 'Shawn Green',
    'map26 - the abandoned mines'           : 'John Romero',
    'map27 - monster condo'                 : 'Sandy Petersen',
    'map28 - the spirit world'              : 'Sandy Petersen',
    'map29 - the living end'                : 'John Romero',
    'map30 - icon of sin'                   : 'Sandy Petersen',
    'map31 - wolfenstein'                   : 'Sandy Petersen',
    'map32 - grosse'                        : 'Sandy Petersen'
}

tnt_maps = {
    'map01 - System Control'                : 'Tom Mustaine',
    'map02 - Human BBQ'                     : 'John Wakelin',
    'map03 - Power Control'                 : 'Robin Patenall & John Minadeo',
    'map04 - Wormhole'                      : 'Ty Halderman',
    'map05 - Hanger'                        : 'Jim Dethlefsen',
    'map06 - Open Season'                   : 'Jimmy Sieben & Ty Halderman',
    'map07 - Prison'                        : 'Andrew Dowswell',
    'map08 - Metal'                         : 'John Minadeo',
    'map09 - Stronghold'                    : 'Jimmy Sieben & Ty Halderman',
    'map10 - Redemption'                    : 'Tom Mustaine',
    'map11 - Storage Facility'              : 'Dean Johnson',
    'map12 - Crater'                        : 'Jim Lowell',
    'map13 - Nukage Processing'             : 'Brian Kidby & Ty Halderman',
    'map14 - Steel Works'                   : 'Robin Patenall',
    'map15 - Dead Zone'                     : 'William D. Whitaker',
    'map16 - Deepest Reaches'               : 'Andre Arsenault',
    'map17 - Processing Area'               : 'Tom Mustaine',
    'map18 - Mill'                          : 'Dario Casali & Ty Halderman',
    'map19 - Shipping/Respawning'           : 'Ty Halderman',
    'map20 - Central Processing'            : "Drake O'Brien",
    'map21 - Administration Center'         : "Drake O'Brien",
    'map22 - Habitat'                       : 'Christopher Buteau',
    'map23 - Lunar Mining Project'          : 'Paul Turnbull',
    'map24 - Quarry'                        : 'Dean Johnson',
    "map25 - Baron's Den"                   : 'Jim Mentzer',
    'map26 - Ballistyx'                     : 'Mark Snell & Jim Lowell',
    'map27 - Mount Pain'                    : "Drake O'Brien",
    'map28 - Heck'                          : 'Milo Casali',
    'map29 - River Styx'                    : 'Jimmy Sieben',
    'map30 - Last Call'                     : 'Jimmy Sieben',
    'map31 - Pharaoh'                       : 'Dario Casali',
    'map32 - Caribbean'                     : 'Dario Casali'
}

plutonia_maps = {
    'map01 - Congo'                         : 'Dario & Milo Casali',
    'map02 - Well of Souls'                 : 'Dario & Milo Casali',
    'map03 - Aztec'                         : 'Dario & Milo Casali',
    'map04 - Caged'                         : 'Dario & Milo Casali',
    'map05 - Ghost Town'                    : 'Dario & Milo Casali',
    "map06 - Baron's Lair"                  : 'Dario & Milo Casali',
    'map07 - Caughtyard'                    : 'Dario & Milo Casali',
    'map08 - Realm'                         : 'Dario & Milo Casali',
    'map09 - Abattoire'                     : 'Dario & Milo Casali',
    'map10 - Onslaught'                     : 'Dario & Milo Casali',
    'map11 - Hunted'                        : 'Dario & Milo Casali',
    'map12 - Speed'                         : 'Dario & Milo Casali',
    'map13 - The Crypt'                     : 'Dario & Milo Casali',
    'map14 - Genesis'                       : 'Dario & Milo Casali',
    'map15 - The Twilight'                  : 'Dario & Milo Casali',
    'map16 - The Omen'                      : 'Dario & Milo Casali',
    'map17 - Compound'                      : 'Dario & Milo Casali',
    'map18 - Neurosphere'                   : 'Dario & Milo Casali',
    'map19 - NME'                           : 'Dario & Milo Casali',
    'map20 - The Death Domain'              : 'Dario & Milo Casali',
    'map21 - Slayer'                        : 'Dario & Milo Casali',
    'map22 - Impossible Mission'            : 'Dario & Milo Casali',
    'map23 - Tombstone'                     : 'Dario & Milo Casali',
    'map24 - The Final Frontier'            : 'Dario & Milo Casali',
    'map25 - The Temple of Darkness'        : 'Dario & Milo Casali',
    'map26 - Bunker'                        : 'Dario & Milo Casali',
    'map27 - Anti-Christ'                   : 'Dario & Milo Casali',
    'map28 - The Sewers'                    : 'Dario & Milo Casali',
    'map29 - Odyssey of Noises'             : 'Dario & Milo Casali',
    'map30 - The Gateway of Hell'           : 'Dario & Milo Casali',
    'map31 - Cyberden'                      : 'Dario & Milo Casali',
    'map32 - Go 2 It'                       : 'Dario & Milo Casali'
}

# TODO: compile full list
# https://web.archive.org/web/20080213013815/http://www.ravengames.com/heretic/insider.php
heretic_maps = {
    'e1m1 - The Docks'                   : 'Michael Raymond-Judy',
    'e1m2 - The Dungeons'                : '',
    'e1m3 - The Gatehouse'               : '',
    'e1m4 - The Guard Tower'             : '',
    'e1m5 - The Citadel'                 : '',
    'e1m6 - The Cathedral'               : '',
    'e1m7 - The Crypts'                  : '',
    "e1m8 - Hell's Maw"                  : '',
    'e1m9 - The Graveyard'               : '',
    'e2m1 - The Crater'                  : '',
    'e2m2 - The Lava Pits'               : '',
    'e2m3 - The River of Fire'           : '',
    'e2m4 - The Ice Grotto'              : '',
    'e2m5 - The Catacombs'               : '',
    'e2m6 - The Labyrinth'               : '',
    'e2m7 - The Great Hall'              : '',
    'e2m8 - The Portals of Chaos'        : '',
    'e2m9 - The Glacier'                 : '',
    'e3m1 - The Storehouse'              : '',
    'e3m2 - The Cesspool'                : '',
    'e3m3 - The Confluence'              : '',
    'e3m4 - The Azure Fortress'          : '',
    'e3m5 - The Ophidian Lair'           : '',
    'e3m6 - The Halls of Fear'           : '',
    'e3m7 - The Chasm'                   : '',
    "e3m8 - D'Sparil's Keep"             : '',
    'e3m9 - The Aquifer'                 : '',
    'e4m1 - Catafalque'                  : 'Michael Raymond-Judy, Brian Raffel & Eric Biessman',
    'e4m2 - Blockhouse'                  : '',
    'e4m3 - Ambulatory'                  : '',
    'e4m4 - Sepulcher'                   : '',
    'e4m5 - Great Stair'                 : '',
    'e4m6 - Halls of the Apostate'       : '',
    'e4m7 - Ramparts of Perdition'       : '',
    'e4m8 - Shattered Bridge'            : '',
    'e4m9 - Mausoleum'                   : '',
    'e5m1 - Ochre Cliffs'                : '',
    'e5m2 - Rapids'                      : '',
    'e5m3 - Quay'                        : '',
    'e5m4 - Courtyard'                   : '',
    'e5m5 - Hydratyr'                    : '',
    'e5m6 - Colonnade'                   : '',
    'e5m7 - Foetid Manse'                : '',
    'e5m8 - Field of Judgement'          : '',
    "e5m9 - Skein of D'Sparil"           : '',
    "e6m1 - Raven's Lair"                : 'Michael Raymond-Judy',
    'e6m2 - Water Shrine'                : 'Brian Raffel',
    "e6m3 - American's Legacy"           : 'Michael Raymond-Judy (after American McGee)'
}

hexen_maps = {
    'map01 - Winnowing Hall'             : '',
    'map02 - Seven Portals'              : '',
    'map03 - Guardian of Ice'            : '',
    'map04 - Guardian of Fire'           : '',
    'map05 - Guardian of Steel'          : '',
    'map06 - Bright Crucible'            : '',
    'map07 - Shadow Wood'                : '',
    'map08 - Darkmere'                   : '',
    'map09 - Caves of Circe'             : '',
    'map10 - Wastelands'                 : '',
    'map11 - Sacred Grove'               : '',
    'map12 - Hypostyle'                  : '',
    'map13 - Shadow Wood'                : '',
    'map14 - Swamp Demo'                 : '',
    'map21 - Forsaken Outpost'           : '',
    'map22 - Castle of Grief'            : '',
    'map23 - Gibbet'                     : '',
    'map24 - Effluvium'                  : '',
    'map25 - Dungeons'                   : '',
    'map26 - Desolate Garden'            : '',
    "map27 - Heresiarch's Seminary"      : '',
    'map28 - Dragon Chapel'              : '',
    'map29 - Nada'                       : '',
    'map30 - Griffin Chapel'             : '',
    'map31 - Deathwind Chapel'           : '',
    'map32 - Orchard of Lamentations'    : '',
    'map33 - Silent Refectory'           : '',
    'map34 - Wolf Chapel'                : '',
    'map35 - Necropolis'                 : '',
    "map36 - Zedek's Tomb"               : '',
    "map37 - Menelkir's Tomb"            : '',
    "map38 - Traductus' Tomb"            : '',
    'map39 - Vivarium'                   : '',
    'map40 - Dark Crucible'              : '',
    'map41 - Maze'                       : ''
}
